### PR TITLE
Make it actually work

### PR DESCRIPTION
**Pull request by StephanHoyer**
it's done by @danioso. I just created the pull request.

### CODE REVIEW

**Comment by gajus** [comment]
@papnkukn Any reason this wasn't merged?

**Comment by rugk** [comment]
?

**Comment by brunosserrao** [comment]
Why didn't you accepted this pull request ? It's solved a problemm to create QR codes.

**Review by papnkukn — APPROVED** [review]

**Review by papnkukn — APPROVED** [review]

**Review by papnkukn — APPROVED** [review]

**Comment by papnkukn** [comment]
@danioso thanks for contributing

**Comment by brunosserrao** [comment]
Great. Thank you @papnkukn and @danioso..

**Pull request merged**
